name: superhero_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http:
  percent_indicator: ^1.0.16
  shared_preferences: ^0.5.2
  provider: ^4.0.1
  flutter_mobx:
  mobx:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  mobx_codegen:

flutter:

  uses-material-design: true

